plugins { id 'com.android.application' }

android {
    namespace 'jp.chisana.foxkifuscanner'
    compileSdk 35
    buildToolsVersion '35.0.0'

    defaultConfig {
        applicationId 'jp.chisana.foxkifuscanner'
        minSdk 30
        targetSdk 35
        versionCode 10203
        versionName '1.2.3-ocr'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.mlkit:text-recognition-japanese:16.0.1'
    implementation 'com.google.mlkit:text-recognition-chinese:16.0.1'
    testImplementation 'junit:junit:4.13.2'
}
